// promiseErrorHandling.js

Promise.reject("ðŸ’¥ Something went wrong")
  .then(() => {
    console.log("âœ… Success"); // Skipped
  })
  .catch(err => {
    console.error("Caught:", err);
  });
